### ISSUE TITLE
The report receives the interrupted status if there are a large number of allure annotations

### ISSUE THREAD

**Issue by AlexMatyushenko** [reportportal/allure-java#30]
**Describe the bug**
If there are a large number of annotations @Owner, @Epic, @Feature, @Story, the report receives the status interrupted and not a single test is displayed in it

**Steps to Reproduce**
1. Run a large number of tests with a large number of Allure annotations

**Expected behavior**
The report in the report portal is generated correctly

**Actual behavior**
The report has status:interrupted. It's empty

**Dependency versions**
agent-allure-testng:5.2.0

![ShooterScreenshot-148-28-02-24](https://github.com/reportportal/allure-java/assets/26823138/5b9c0f24-fb1e-4f17-9d80-5a3acc27fff5)

**Comment by HardNorth** [comment]
@AlexMatyushenko, It's not clear what's exactly happening with the Launch, what mades it interrupted. And we don't have "a large number of tests with a large number of Allure annotations" in our test suite to reproduce it. Can you have a look into agent / server logs for errors?

**Comment by AlexMatyushenko** [comment]
@HardNorth where can I see the agent log?

**Comment by HardNorth** [comment]
@AlexMatyushenko in the console during the execution, do you see any errors there?

**Comment by AlexMatyushenko** [comment]
@HardNorth no, the test runs correctly

**Comment by AlexMatyushenko** [comment]
Can I exclude these annotations from the reporting report? They have no functionality and are displayed like this
![ShooterScreenshot-149-29-02-24](https://github.com/reportportal/allure-java/assets/26823138/22f90bc3-0875-45d8-9319-c84bc7105337)

**Comment by AlexMatyushenko** [comment]
@HardNorth i need help

**Comment by HardNorth** [comment]
@AlexMatyushenko How did you actually even managed to include such many annotations? Do you have a class with all these annotations? Or they duplicate somehow?

**Comment by AlexMatyushenko** [comment]
@HardNorth Large project, many tests, so many different annotations

**Comment by HardNorth** [comment]
@AlexMatyushenko I don't believe such amount of attributes is even usable, neither in Allure nor in ReportPortal. It's looks like misuse for me, attributes for sake of attributes per se. So I can only recommend reorganise them to some reasonable amount.

**Comment by HardNorth** [comment]
@AlexMatyushenko There is alway an option to internalize our library, extend `AllureAwareService.java`, override, for instance, [buildStartTestItemRq](https://github.com/reportportal/allure-java/blob/develop/agent-allure-testng/src/main/java/com/epam/reportportal/testng/AllureAwareService.java#L54) method and filter out redundant attributes.

**Comment by AlexMatyushenko** [comment]
@HardNorth thanks, I will take a look
